[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
owomi = "CAExaUGyDw6HR93CuXipA2oXTf1QGnGpxeWSAJjFQx7p"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/byte/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
